name: hello world
on: workflow_dispatch
jobs:
 say-hello-world:
   runs-on: ubuntu-latest
   steps:
   - name: print hello world
     run: echo "hello world, Github Action!"
 say-goodby:
    needs: say-hello-world
    runs-on: ubuntu-latest
    steps:
    - name: start goodby
      run: echo "goodby,Github Action!"
      
      
